import { OPERATION_RIGHT_HIDE } from '@digital-first/df-app-core'

export const OPERATION_PMO_HANDLING_ADVICE = 'pmohandlingadvice'
export const OPERATION_PMC_HANDLING_ADVICE = 'pmchandlingadvice'
export const OPERATION_PLANNER = 'planner'

export const OPERATION_DEFAULTS = {}

OPERATION_DEFAULTS[OPERATION_PMO_HANDLING_ADVICE] = OPERATION_RIGHT_HIDE
OPERATION_DEFAULTS[OPERATION_PMC_HANDLING_ADVICE] = OPERATION_RIGHT_HIDE
OPERATION_DEFAULTS[OPERATION_PLANNER] = OPERATION_RIGHT_HIDE